# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', jsonfield.fields.JSONField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('key', models.CharField(db_index=True, default=b'##default_key##', max_length=100)),
                ('schedule_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('html_content', models.TextField()),
                ('should_inline', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=False)),
                ('from_address', models.CharField(max_length=255)),
                ('blacklist', jsonfield.fields.JSONField(blank=True)),
                ('quota', models.IntegerField(default=15000)),
                ('usage', models.IntegerField(default=0)),
                ('quota_type_is_daily', models.BooleanField(default=False)),
                ('preference', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='deferredmail',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asyncmailer.EmailTemplate'),
        ),
    ]
